#!/bin/bash
clear
#flagging procedure
while getopts ":f:l:" opt; do
  case $opt in
    f) first="$OPTARG"
    ;;
    l) last="$OPTARG"
    ;;
    \?) echo "Invalid option -$OPTARG" >&2
    ;;
  esac
done

urlhead=ftp://legacy.gsfc.nasa.gov/nicer/data/.obs2validate/
#Start at June, the first obs dates
month=6

#Find the first month
if [ $first -ge 1000000000 ];
then
	until curl --output /dev/null --silent --fail -r 0-0 "${urlhead}2017_0${month}/${first}.tar" || curl --output /dev/null --silent --fail -r 0-0 "${urlhead}2017_${month}/${first}.tar" || curl --output /dev/null --silent --fail -r 0-0 "${urlhead}2018_0${month}/${first}.tar"; do
	        if [ $month == 12 ]; then month=1
        	else
                	month=`expr $month + 1`
        	fi
	done
else
	until curl --output /dev/null --silent --fail -r 0-0 "${urlhead}2017_0${month}/00${first}.tar" || curl --output /dev/null --silent --fail -r 0-0 "${urlhead}2017_${month}/00${first}.tar" || curl --output /dev/null --silent --fail -r 0-0 "${urlhead}2018_0${month}/00${first}.tar"; do
        	if [ $month == 12 ]; then month=1
        	else
                	month=`expr $month + 1`
        	fi
	done
fi

echo The month of the first obs is $month


if [ $first -ge 1000000000 ];
then
echo "No zeros needed"
for i in $(seq $first $last); do

if [ $month -lt 10 ];
then
  if [ $month -lt 6 ];
  then
    url=${urlhead}2018_0${month}/${i}.tar
  else
    url=${urlhead}2017_0${month}/${i}.tar
  fi
else
  url=${urlhead}2017_${month}/${i}.tar
fi


if curl --output /dev/null --silent --fail -r 0-0 "$url"; then
  echo "URL exists: $url"
  curl -O $url
else
  echo "URL does not exist: changing month"
  until curl --output /dev/null --silent --fail -r 0-0 "${urlhead}2017_0${month}/${i}.tar" || curl --output /dev/null --silent --fail -r 0-0 "${urlhead}2017_${month}/${i}.tar" || curl --output /dev/null --silent --fail -r 0-0 "${urlhead}2018_0${month}/${i}.tar"; do
	if [ $month == 12 ]; then month=1
        	else
                	month=`expr $month + 1`
        fi
  done
  echo The month for $i is $month
  if [ $month -lt 10 ];
  then
    if [ $month -lt 6 ];
    then
	url=${urlhead}2018_0${month}/${i}.tar
    else
    	url=${urlhead}2017_0${month}/${i}.tar
    fi
  else
    url=${urlhead}2017_${month}/${i}.tar
  fi

  curl -O $url
fi

done

else
echo "Zeros needed"
for i in $(seq $first $last); do

if [ $month -lt 10 ];
then
  if [ $month -lt 6 ];
  then
    url=${urlhead}2018_0${month}/00${i}.tar
  else
    url=${urlhead}2017_0${month}/00${i}.tar
  fi
else
  url=${urlhead}2017_${month}/00${i}.tar
fi


if curl --output /dev/null --silent --fail -r 0-0 "$url"; then
  echo "URL exists: $url"
  curl -O $url
else
  echo "URL does not exist: changing month"
  until curl --output /dev/null --silent --fail -r 0-0 "${urlhead}2017_0${month}/00${i}.tar" || curl --output /dev/null --silent --fail -r 0-0 "${urlhead}2017_${month}/00${i}.tar" || curl --output /dev/null --silent --fail -r 0-0 "${urlhead}2018_0${month}/00${i}.tar"; do
	if [ $month == 12 ]; then month=1
        	else
                	month=`expr $month + 1`
        fi
  done
  echo The month for $i is $month
  if [ $month -lt 10 ];
  then
    if [ $month -lt 6 ];
    then
	url=${urlhead}2018_0${month}/00${i}.tar
    else
    	url=${urlhead}2017_0${month}/00${i}.tar
    fi
  else
    url=${urlhead}2017_${month}/00${i}.tar
  fi

  curl -O $url
fi

done
fi
