#!/usr/bin/env python
from __future__ import print_function, division
import os, sys
import matplotlib.pyplot as plt
import numpy as np
import argparse
from astropy import log
from os import path
from glob import glob
from subprocess import check_call
import shutil
from astropy.table import Table
import sys
from nicer.values import *

desc = """
This pulls the unfiltered exposure for a specific obs ID
"""

parser = argparse.ArgumentParser(description = desc)
parser.add_argument("--obs", help="Input obs ID", default=None)
parser.add_argument("--sum", help="If True, will sum over all files in current directory", default=False)
args = parser.parse_args()

if not args.sum:
	mpu7 = args.obs + "/xti/event_cl/ni" + args.obs + "_0mpu7_ufa.evt"
	evttable = Table.read(mpu7,hdu=2)
	exposure = sum(evttable["STOP"] - evttable["START"])
	print(exposure)
if args.sum:
	exposure = 0
	for filename in os.listdir(os.getcwd()):
		if os.path.isfile(filename+"/xti/event_cl/ni"+filename+"_0mpu7_ufa.evt"):
			mpu7 = filename + "/xti/event_cl/ni" + filename + "_0mpu7_ufa.evt"
			evttable = Table.read(mpu7, hdu=2)
			exposure += sum(evttable["STOP"] - evttable["START"])
	print(exposure)	
