#!/bin/bash
clear
# HOW TO USE
# This is a more automatic version of the original run_pipeline. 
# Works only with sequential obsIDs (i.e. increase by 1)
# Use the flag -f for first obsID
# Use the flag -l for the last obsID
# Use the flag -p to specify the path to the par file
# Note that this code does not currently have the option for adding extra commands to the pipeline. You will have to add them manually for now. 

#Dom 2018

#flagging procedure
while getopts ":f:l:p:" opt; do
  case $opt in
    f) first="$OPTARG"
    ;;
    l) last="$OPTARG"
    ;;
    p) par="$OPTARG"
    ;;
    \?) echo "Invalid option -$OPTARG" >&2
    ;;
  esac
done

#First go through and decrypt it all
find . -name '*tar' -exec tar xvfp {} \; -exec rm -f {} \;
find . -name '*.gpg' -exec ls {} \; | gpg --decrypt-files
#Now do all the gunzip and gpg removal
echo Gunziping all files
find . -name '*gz' -exec rm -f {} \;
echo Removing gpg files
find . -name 'gpg' -exec rm -f {} \;
#Finally run the pipeline
# Could just implement the functionality for a list of files now, rather than looping through obsids, but will only do that if I have time. Wrote a quick little code that creates such lists elsewhere, just reference that, create the lists, then call psrpipe with @ (could also get a free merge option from that which would be nice)
for i in $(seq $first $last); do
	if [ $first -lt 1000000000 ]; then i=00$i;fi

	if [ -z "$par" ];
	then
		psrpipe.py --cormin 5 $i --filtpolar
	else
		psrpipe.py --par $par --cormin 5 $i --filtpolar
	fi
done
