#!/bin/bash

. /packages/heasoft-6.27.2/x86_64-pc-linux-gnu-libc2.23/headas-init.sh

cd /students/pipeline/heasoft6.27/PSR_B1937+21

/packages/python3.6.8/bin/python /homes/pipeline/scripts/LommenResearchGroup/pipeline/pulsar_pipe.py --update PSR_1937+21 --user nicer_team --passwd sextant --k_file ~/decrypt_key --par /students/pipeline/parfiles/PSR_B1937+21.par.nancaytzr --silent_curl

echo -n 'Completed PSR_B1937+21 ' >> ~/cron_log.txt
date >> ~/cron_log.txt

