#!/bin/bash

. /packages/heasoft-6.27.2/x86_64-pc-linux-gnu-libc2.23/headas-init.sh

cd /students/pipeline/heasoft6.27/BKGD_RXTE

/packages/python3.6.8/bin/python /homes/pipeline/scripts/LommenResearchGroup/pipeline/background_pipe.py --update --user nicer_team --passwd sextant --k_file ~/decrypt_key --par --silent_curl

echo -n 'Completed BKGD_RXTE ' >> ~/cron_log.txt
date >> ~/cron_log.txt

